services:
  - type: web
    name: nigam-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_FLAGS
        value: "--legacy-peer-deps=false"
